[window]

decorations = "None"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[keyboard]
bindings = [
  { key = "P", mods = "Control", action = "ReceiveChar" },
  { key = "N", mods = "Control", action = "ReceiveChar" },
  { key = "/", mods = "Alt", action = "None" },
  { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
  { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
  { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
  { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
  { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
  { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
  { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
  { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
  { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
  { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
]
